export const adminEndpoints = {
  apiKeys: {
    v1: {
      base: '/api/v1/me/api_key',
      count: '/api/v1/me/api_key/count',
      ids: '/api/v1/me/api_key/ids',
      schema: '/api/v1/me/api_key/schema',
    },
    v2: {
      base: '/api/v2/api_key',
      count: '/api/v2/api_key/count',
      ids: '/api/v2/api_key/ids',
      schema: '/api/v2/api_key/schema',
    },
  },
  roles: {
    base: '/api/v1/admin/role',
    count: '/api/v1/admin/role/count',
    ids: '/api/v1/admin/role/ids',
    schema: '/api/v1/admin/role/schema',
    byRole: '/api/v1/role/:role',
    inherited: '/api/v1/role/:role/inherited',
  },
  users: {
    base: '/api/v1/admin/users',
    count: '/api/v1/admin/users/count',
    ids: '/api/v1/admin/users/ids',
    schema: '/api/v1/admin/users/schema',
    groups: '/api/v1/admin/users/:user/groups',
    roles: '/api/v1/admin/users/:user/roles',
    attachGroup: '/api/v1/admin/users/:user/group/:userGroup',
    detachGroup: '/api/v1/admin/users/:user/group/:userGroup',
  },
  userGroups: {
    base: '/api/v1/admin/user_group',
    count: '/api/v1/admin/user_group/count',
    ids: '/api/v1/admin/user_group/ids',
    schema: '/api/v1/admin/user_group/schema',
    attachUser: '/api/v1/user_group/:userGroup/user/:user',
    detachUser: '/api/v1/user_group/:userGroup/user/:user',
    users: '/api/v1/user_group/:userGroup/users',
  },
  configuration: {
    base: '/api/v1/admin/configuration',
    count: '/api/v1/admin/configuration/count',
    ids: '/api/v1/admin/configuration/ids',
    schema: '/api/v1/admin/configuration/schema',
  },
  companies: {
    base: '/api/v1/admin/companies',
    schema: '/api/v1/admin/companies/schema',
    members: '/api/v1/companies/:companyId/members',
    memberships: '/api/v1/companies/:companyId/memberships',
    memberByUser: '/api/v1/companies/:companyId/members/:userId',
    projects: '/api/v1/companies/:id/projects',
    sprints: '/api/v1/admin/companies/:id/sprints',
  },
  candidates: {
    base: '/api/v1/admin/candidates',
    schema: '/api/v1/admin/candidates/schema',
  },
  jobApplications: {
    base: '/api/v1/admin/job-applications',
    myOffers: '/api/v1/admin/job-applications/my-offers',
    accept: '/api/v1/admin/job-applications/:id/accept',
    reject: '/api/v1/admin/job-applications/:id/reject',
    withdraw: '/api/v1/admin/job-applications/:id/withdraw',
  },
  jobOffers: {
    base: '/api/v1/admin/job-offers',
    facets: '/api/v1/admin/job-offers/facets',
    my: '/api/v1/admin/job-offers/my',
    available: '/api/v1/admin/job-offers/available',
    apply: '/api/v1/admin/job-offers/:id/apply',
  },
  offers: { base: '/api/v1/admin/offers', schema: '/api/v1/admin/offers/schema' },
  resumes: { base: '/api/v1/admin/resumes', my: '/api/v1/admin/resumes/my', schema: '/api/v1/admin/resumes/schema' },
  resumeEducation: { base: '/api/v1/admin/resume-education', schema: '/api/v1/admin/resume-education/schema' },
  resumeExperiences: { base: '/api/v1/admin/resume-experiences', schema: '/api/v1/admin/resume-experiences/schema' },
  resumeLanguages: { base: '/api/v1/me/resumes/:resumeId/languages' },
  resumeProjects: { base: '/api/v1/me/resumes/:resumeId/projects' },
  resumeReferences: { base: '/api/v1/me/resumes/:resumeId/references' },
  resumeSkills: { base: '/api/v1/admin/resume-skills', schema: '/api/v1/admin/resume-skills/schema' },
  media: {
    base: '/api/v1/admin/media',
    schema: '/api/v1/admin/media/schema',
    upload: '/api/v1/admin/media/upload',
    exportExcel: '/api/v1/admin/media/export/:configurationId/excel',
    exportPdf: '/api/v1/admin/media/export/:configurationId/pdf',
  },
  notifications: {
    base: '/api/v1/admin/notifications',
    unreadCount: '/api/v1/admin/notifications/users/:id/unread-count',
  },
  blog: {
    comments: { base: '/api/v1/admin/blog-comments', schema: '/api/v1/admin/blog-comments/schema' },
    posts: { base: '/api/v1/admin/blog-posts', schema: '/api/v1/admin/blog-posts/schema' },
    postLinks: { base: '/api/v1/admin/blog-post-links', schema: '/api/v1/admin/blog-post-links/schema' },
    tags: { base: '/api/v1/admin/blog-tags', schema: '/api/v1/admin/blog-tags/schema' },
  },
  projects: {
    base: '/api/v1/admin/projects',
    schema: '/api/v1/admin/projects/schema',
    tasks: '/api/v1/admin/projects/:id/tasks',
  },
  sprints: { base: '/api/v1/admin/sprints', schema: '/api/v1/admin/sprints/schema' },
  tasks: {
    base: '/api/v1/admin/tasks',
    schema: '/api/v1/admin/tasks/schema',
    start: '/api/v1/admin/tasks/:id/start',
    complete: '/api/v1/admin/tasks/:id/complete',
    archive: '/api/v1/admin/tasks/:id/archive',
    reopen: '/api/v1/admin/tasks/:id/reopen',
    requests: '/api/v1/admin/tasks/:id/task-requests',
  },
  taskRequests: {
    base: '/api/v1/admin/task-requests',
    schema: '/api/v1/admin/task-requests/schema',
    groupedByTask: '/api/v1/admin/task-requests/sprints/:sprintId/grouped-by-task',
    setRequester: '/api/v1/admin/task-requests/:id/requester/:requesterId',
    setReviewer: '/api/v1/admin/task-requests/:id/reviewer/:reviewerId',
    setSprint: '/api/v1/admin/task-requests/:id/sprint/:sprintId',
    setRequestedStatus: '/api/v1/admin/task-requests/:id/requested-status/:status',
  },
  quizzes: { base: '/api/v1/admin/quizzes', schema: '/api/v1/admin/quizzes/schema' },
  calendarEvents: { base: '/api/v1/admin/calendar/events', schema: '/api/v1/admin/calendar/events/schema' },
  statistics: {
    overview: '/api/v1/admin/statistics/overview',
    entities: '/api/v1/admin/statistics/entities',
    timeseries: '/api/v1/admin/statistics/timeseries',
    timeseriesByEntity: '/api/v1/admin/statistics/timeseries/:entity',
    statusesDistribution: '/api/v1/admin/statistics/distributions/statuses',
  },
} as const

export function withPathParams(path: string, params: Record<string, string | number>) {
  return Object.entries(params).reduce(
    (resolvedPath, [key, value]) => resolvedPath.replaceAll(`{$:key}`, encodeURIComponent(String(value))),
    path,
  )
}
